### ISSUE TITLE
Can you add mode details here

### ISSUE THREAD

**Issue by ajacreations** [anilectjose/Internship#3]
It will be better if you add more here
6c34f4a338b1457850789d7a3a5247ac98f45128

**Comment by anilectjose** [comment]
Sure, I'm working on that.

**Comment by ajacreations** [comment]
Really thankyou for considering my issue
it will be better if you provide this too
[GitHub](http://github.com/ajacreations)

**Comment by anilectjose** [comment]
Sure, Let me change it.

**Comment by ajacreations** [comment]
Thank you
