### ISSUE TITLE
There is no respect in this comment

### ISSUE THREAD

**Issue by anilectjose** [anilectjose/Internship#4]
Thank you
He just that only
_Originally posted by @ajacreations in https://github.com/anilectjose/Internship/issues/3#issuecomment-835844682_

**Comment by ajacreations** [comment]
Sorry i didn't mean that

**Comment by anilectjose** [comment]
Ok then leave it
fix #4

**Comment by ajacreations** [comment]
Sure i will

**Comment by anilectjose** [comment]
> Sorry i didn't mean that

Can you stop
